### ISSUE TITLE
`nixos-rebuild switch` often hangs at during the "switching to new configuration" phase

### ISSUE THREAD

**Issue by alastairong** [Holo-Host/bugs-n-issues#27]
This happens with what seems to be varying severity depending on what configuration the HoloPort is being switched to.

I've seen cases where it resolves after ~30 minutes and cases were it hangs for seemingly indefinitely.

When we're ready to start this let me know and I'll find the most appropriate examples for investigation / reproduction.

**Comment by peeech** [comment]
Most likely what you are seeing here is the phase of restarting services.`nixos-rebuild switch` will wait for all the services to enter successful state. If there is one service that freezes somewhere during restart entire rebuild will keep waiting for it.

Suggested way forward is when you see it next time happen cancel rebuild and type `systemctl --failed`. This will give you more information on what is blocking rebuild. Lemme know once you read this so we can close an issue and open more specific one once you see another rebuild freeze. @alastairong

**Comment by alastairong** [comment]
Sure I can do that. And yes it gets stuck on the phase of restarting services.

**Comment by alastairong** [comment]
@peeech Re-opening this with more detail. 

Experiencing this when switching from `master` to PR `1134` (just off `develop`)

Hanging here:

```
setting up tmpfiles
reloading the following units: dbus.service, dev-hugepages.mount, dev-mqueue.mount, firewall.service, sys-kernel-debug.mount
restarting the following units: dhcpcd.service, nginx.service, sshd.service, systemd-journald.service
starting the following units: acme-fixperms.service, audit.service, auto-upgrade.timer, configure-holochain.service, cpufreq.service, holo-auth-client.service, holo-auth-notifier.service, holo-auto-installer.timer, holo-envoy.service, holo-router-agent.timer, holochain.service, hp-admin-crypto-server.service, hpos-admin-api.service, hpos-holochain-api.service, hpos-init.service, hpos-led-manager.service, kmod-static-nodes.service, lair-keystore.service, network-local-commands.service, network-setup.service, nix-daemon.socket, nix-gc.timer, nscd.service, resolvconf.service, systemd-modules-load.service, systemd-sysctl.service, systemd-timesyncd.service, systemd-tmpfiles-clean.timer, systemd-tmpfiles-setup-dev.service, systemd-udev-trigger.service, systemd-udevd-control.socket, systemd-udevd-kernel.socket, zerotierone.service
A dependency job for configure-holochain.service failed. See 'journalctl -xe' for details.

```

**Comment by alastairong** [comment]
Looks to be acme service:

```
[root@hpos:~]# systemctl --failed
  UNIT                LOAD   ACTIVE SUB    DESCRIPTION
● acme-devNet.service loaded failed failed Renew ACME certificate for devNet

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.
1 loaded units listed.
```

**Comment by alastairong** [comment]
acme-devNet logs:

```
Mar 02 11:55:30 hpos holo-router-acme[5322]: }
Mar 02 11:55:30 hpos holo-router-acme[5322]: 2022-03-02 11:55:30,378:DEBUG:urllib3.connectionpool:452: https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 386
Mar 02 11:55:30 hpos holo-router-acme[5322]: 2022-03-02 11:55:30,379:DEBUG:acme.client:1215: Received response:
Mar 02 11:55:30 hpos holo-router-acme[5322]: HTTP 201
Mar 02 11:55:30 hpos holo-router-acme[5322]: Server: nginx
Mar 02 11:55:30 hpos holo-router-acme[5322]: Date: Wed, 02 Mar 2022 11:55:30 GMT
Mar 02 11:55:30 hpos holo-router-acme[5322]: Content-Type: application/json
Mar 02 11:55:30 hpos holo-router-acme[5322]: Content-Length: 386
Mar 02 11:55:30 hpos holo-router-acme[5322]: Connection: keep-alive
Mar 02 11:55:30 hpos holo-router-acme[5322]: Boulder-Requester: 433003030
Mar 02 11:55:30 hpos holo-router-acme[5322]: Cache-Control: public, max-age=0, no-cache
Mar 02 11:55:30 hpos holo-router-acme[5322]: Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Mar 02 11:55:30 hpos holo-router-acme[5322]: Location: https://acme-v02.api.letsencrypt.org/acme/order/433003030/68149910840
Mar 02 11:55:30 hpos holo-router-acme[5322]: Replay-Nonce: 0002g3QVZsEod7WhbDsh8E-Ddpln5EKckY5YYroO42ymSjE
Mar 02 11:55:30 hpos holo-router-acme[5322]: X-Frame-Options: DENY
Mar 02 11:55:30 hpos holo-router-acme[5322]: Strict-Transport-Security: max-age=604800
Mar 02 11:55:30 hpos holo-router-acme[5322]: {
Mar 02 11:55:30 hpos holo-router-acme[5322]:   "status": "pending",
Mar 02 11:55:30 hpos holo-router-acme[5322]:   "expires": "2022-03-09T11:55:30Z",
Mar 02 11:55:30 hpos holo-router-acme[5322]:   "identifiers": [
Mar 02 11:55:30 hpos holo-router-acme[5322]:     {
Mar 02 11:55:30 hpos holo-router-acme[5322]:       "type": "dns",
Mar 02 11:55:30 hpos holo-router-acme[5322]:       "value": "2hnl9nvy7jvrafxa1vmw1me85s34b2776gvy013nelumm1gsb8.holohost.dev"
Mar 02 11:55:30 hpos holo-router-acme[5322]:     }
Mar 02 11:55:30 hpos holo-router-acme[5322]:   ],
Mar 02 11:55:30 hpos holo-router-acme[5322]:   "authorizations": [
Mar 02 11:55:30 hpos holo-router-acme[5322]:     "https://acme-v02.api.letsencrypt.org/acme/authz-v3/83596917750"
Mar 02 11:55:30 hpos holo-router-acme[5322]:   ],
Mar 02 11:55:30 hpos holo-router-acme[5322]:   "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/433003030/68149910840"
Mar 02 11:55:30 hpos holo-router-acme[5322]: }
Mar 02 11:55:30 hpos holo-router-acme[5322]: 2022-03-02 11:55:30,380:DEBUG:acme.client:1245: Storing nonce: 0002g3QVZsEod7WhbDsh8E-Ddpln5EKckY5YYroO42ymSjE
Mar 02 11:55:30 hpos holo-router-acme[5322]: 2022-03-02 11:55:30,383:DEBUG:acme.client:1073: JWS payload:
Mar 02 11:55:30 hpos holo-router-acme[5322]: b''
Mar 02 11:55:30 hpos holo-router-acme[5322]: 2022-03-02 11:55:30,396:DEBUG:acme.client:1165: Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/83596917750:
Mar 02 11:55:30 hpos holo-router-acme[5322]: {
Mar 02 11:55:30 hpos holo-router-acme[5322]:   "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvNDMzMDAzMDMwIiwgIm5vbmNlIjogIjAwMDJnM1FWWnNFb2Q3V2hiRHNoOEUtRGRwbG41RUtja1k1WVlyb080MnltU2pFIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My84MzU5NjkxNzc1MCJ9",
Mar 02 11:55:30 hpos holo-router-acme[5322]:   "signature": "GljmOv9CtKIqhpeRJYeqK3DschtQWHBCrbbUeS_E104typz8iPskBLVyJ92flt8RWAXoy3v-VTZxMY5npGSrPtMO2IANaC6ReCkzGXAT9s9i9qiqcvphBkJ8or2WxbAbhrXgK-wELiaxQLX7vD5P45N7vNT8CCYzWYeIvdXDos6_tzWwbthfBjlMhiyX4VkQQ2bHDqnQqxBu1KVPGxjlT3N4x1TneaD3t5M4_DyxyEz2hSWzGHqKkzdOkOw9xE2ZWNAbpaNuRnHs1eIYIveuPb2s7_skMF6J0HP4XzRIJ2KfGPi21xfefsk1pz1zgydCDZInl6bCCkCA-CgBnJi3s7DtURbeO81SaJkgWz30F78H4tCiEKwyVoLfDsQZ8JIWRPpeore5X1-VRnxTLemNmlU9G2OQzNeHPqK1VtEn_FzAOVqEYMdoENNfIfGyAq3RwtAZekfbBFJpEfV0I9P2mvv371SLZXXjGSNLmNgRRIN7kFToVknTMW6OKQ9kRoaEXes6bZl1hP3aT5SZE4axWlpCKgIMaQHEBtxn-hzO0Ryx-f_vqajVsL4W4uHtilZa0MQ8Z2ZORgmnyBhcmIf_WPtRsVGEayoEcZvkWV5MUNWXyluaBk0ihLouCBS4TbtApfKo5-O8rOFFRdRTkRGfZzU8QeqtdZ5vvxSPwzATsbs",
Mar 02 11:55:30 hpos holo-router-acme[5322]:   "payload": ""
Mar 02 11:55:30 hpos holo-router-acme[5322]: }
Mar 02 11:55:30 hpos holo-router-acme[5322]: 2022-03-02 11:55:30,541:DEBUG:urllib3.connectionpool:452: https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/83596917750 HTTP/1.1" 200 844
Mar 02 11:55:30 hpos holo-router-acme[5322]: 2022-03-02 11:55:30,543:DEBUG:acme.client:1215: Received response:
Mar 02 11:55:30 hpos holo-router-acme[5322]: HTTP 200
Mar 02 11:55:30 hpos holo-router-acme[5322]: Server: nginx
Mar 02 11:55:30 hpos holo-router-acme[5322]: Date: Wed, 02 Mar 2022 11:55:30 GMT
Mar 02 11:55:30 hpos holo-router-acme[5322]: Content-Type: application/json
Mar 02 11:55:30 hpos holo-router-acme[5322]: Content-Length: 844
Mar 02 11:55:30 hpos holo-router-acme[5322]: Connection: keep-alive
Mar 02 11:55:30 hpos holo-router-acme[5322]: Boulder-Requester: 433003030
Mar 02 11:55:30 hpos holo-router-acme[5322]: Cache-Control: public, max-age=0, no-cache
Mar 02 11:55:30 hpos holo-router-acme[5322]: Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Mar 02 11:55:30 hpos holo-router-acme[5322]: Replay-Nonce: 00015dEG1wA87s1kzwWs7SNKnkrT4pyJhhOkU-x4YNW9kyQ
Mar 02 11:55:30 hpos holo-router-acme[5322]: X-Frame-Options: DENY
Mar 02 11:55:30 hpos holo-router-acme[5322]: Strict-Transport-Security: max-age=604800
Mar 02 11:55:30 hpos holo-router-acme[5322]: {
Mar 02 11:55:30 hpos holo-router-acme[5322]:   "identifier": {
Mar 02 11:55:30 hpos holo-router-acme[5322]:     "type": "dns",
Mar 02 11:55:30 hpos holo-router-acme[5322]:     "value": "2hnl9nvy7jvrafxa1vmw1me85s34b2776gvy013nelumm1gsb8.holohost.dev"
Mar 02 11:55:30 hpos holo-router-acme[5322]:   },
Mar 02 11:55:30 hpos holo-router-acme[5322]:   "status": "pending",
Mar 02 11:55:30 hpos holo-router-acme[5322]:   "expires": "2022-03-09T11:55:30Z",
Mar 02 11:55:30 hpos holo-router-acme[5322]:   "challenges": [
Mar 02 11:55:30 hpos holo-router-acme[5322]:     {
Mar 02 11:55:30 hpos holo-router-acme[5322]:       "type": "http-01",
Mar 02 11:55:30 hpos holo-router-acme[5322]:       "status": "pending",
Mar 02 11:55:30 hpos holo-router-acme[5322]:       "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/83596917750/2wzFhg",
Mar 02 11:55:30 hpos holo-router-acme[5322]:       "token": "lbMqxPjEExdHKaBUhmWISjTYMbQKNvkKmoQ5gmI5wAk"
Mar 02 11:55:30 hpos holo-router-acme[5322]:     },
Mar 02 11:55:30 hpos holo-router-acme[5322]:     {
Mar 02 11:55:30 hpos holo-router-acme[5322]:       "type": "dns-01",
Mar 02 11:55:30 hpos holo-router-acme[5322]:       "status": "pending",
Mar 02 11:55:30 hpos holo-router-acme[5322]:       "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/83596917750/_kPLVQ",
Mar 02 11:55:30 hpos holo-router-acme[5322]:       "token": "lbMqxPjEExdHKaBUhmWISjTYMbQKNvkKmoQ5gmI5wAk"
Mar 02 11:55:30 hpos holo-router-acme[5322]:     },
Mar 02 11:55:30 hpos holo-router-acme[5322]:     {
Mar 02 11:55:30 hpos holo-router-acme[5322]:       "type": "tls-alpn-01",
Mar 02 11:55:30 hpos holo-router-acme[5322]:       "status": "pending",
Mar 02 11:55:30 hpos holo-router-acme[5322]:       "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/83596917750/AVUDuw",
Mar 02 11:55:30 hpos holo-router-acme[5322]:       "token": "lbMqxPjEExdHKaBUhmWISjTYMbQKNvkKmoQ5gmI5wAk"
Mar 02 11:55:30 hpos holo-router-acme[5322]:     }
Mar 02 11:55:30 hpos holo-router-acme[5322]:   ]
Mar 02 11:55:30 hpos holo-router-acme[5322]: }
Mar 02 11:55:30 hpos holo-router-acme[5322]: 2022-03-02 11:55:30,543:DEBUG:acme.client:1245: Storing nonce: 00015dEG1wA87s1kzwWs7SNKnkrT4pyJhhOkU-x4YNW9kyQ
Mar 02 11:55:30 hpos holo-router-acme[5322]: Traceback (most recent call last):
Mar 02 11:55:30 hpos holo-router-acme[5322]:   File "/nix/store/s86rgdzf98yxbqyy3410710l7kncarq1-simp_le-client-0.17.0/lib/python3.9/site-packages/simp_le.py", line 1565, in main
Mar 02 11:55:30 hpos holo-router-acme[5322]:     return main_with_exceptions(cli_args)
Mar 02 11:55:30 hpos holo-router-acme[5322]:   File "/nix/store/s86rgdzf98yxbqyy3410710l7kncarq1-simp_le-client-0.17.0/lib/python3.9/site-packages/simp_le.py", line 1549, in main_with_exceptions
Mar 02 11:55:30 hpos holo-router-acme[5322]:     persist_new_data(args, existing_data)
Mar 02 11:55:30 hpos holo-router-acme[5322]:   File "/nix/store/s86rgdzf98yxbqyy3410710l7kncarq1-simp_le-client-0.17.0/lib/python3.9/site-packages/simp_le.py", line 1438, in persist_new_data
Mar 02 11:55:30 hpos holo-router-acme[5322]:     save_validation(roots[name], challb, validation)
Mar 02 11:55:30 hpos holo-router-acme[5322]:   File "/nix/store/s86rgdzf98yxbqyy3410710l7kncarq1-simp_le-client-0.17.0/lib/python3.9/site-packages/simp_le.py", line 1078, in save_validation
Mar 02 11:55:30 hpos holo-router-acme[5322]:     os.makedirs(os.path.join(root, challb.URI_ROOT_PATH))
Mar 02 11:55:30 hpos holo-router-acme[5322]:   File "/nix/store/2c9w4p2x6x0l64fdvcmc11app7x4xran-python3-3.9.6/lib/python3.9/os.py", line 225, in makedirs
Mar 02 11:55:30 hpos holo-router-acme[5322]:     mkdir(name, mode)
Mar 02 11:55:30 hpos holo-router-acme[5322]: PermissionError: [Errno 13] Permission denied: '/var/lib/acme/acme-challenge/.well-known/acme-challenge'
Mar 02 11:55:30 hpos holo-router-acme[5322]: Unhandled error has happened, traceback is above
Mar 02 11:55:30 hpos holo-router-acme[5322]: Debugging tips: -v improves output verbosity. Help is available under --help.
Mar 02 11:55:30 hpos systemd[1]: acme-devNet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 02 11:55:30 hpos systemd[1]: acme-devNet.service: Failed with result 'exit-code'.
```

**Comment by peeech** [comment]
Fixed in https://github.com/Holo-Host/holo-nixpkgs/pull/1219
